spring:
  profiles:
    active:dev
    
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-dev
       
---
server:
  port: 7011
spring:
  profiles:test
  application:
    name: springcloud-test

#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #修改Eureka上的默认描述信息
    instance-id: springcloud-provider-dept8003




